config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show] # ユーザーマイページへのルーティング

  resources :hobbies do
    resources:likes,only:[:create,:destroy] #create アクションと destroy アクションのみしか使わない
  end

  root 'hobbies#index'

    # ネストさせる
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :rooms, only: [:show, :create, :index] do
      member do
        get 'inviting' => 'users#invite'
        post '/users/:user_id/entries' => 'entries#create', as: 'entries'
      end
    end
  

    delete 'rooms/:room_id/users/:user_id/entries' => 'entries#destroy', as: 'entry'

    resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

  belongs_to :user
  belongs_to :room
  
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to:user
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    #自分をフォローしているユーザー
    belongs_to :follower, class_name: "User"

    #自分がフォローしているユーザー
    belongs_to :following, class_name: "User"

    #バリデーション
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms
  has_many :users, through: :user_rooms
  has_many :posts
  has_many :entries
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def create 
    @entry=Entry.create(room_id:params[:id], user_id:params[:user_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @entry = Entry.find_by(room_id: params[:room_id], user_id: params[:user_id])
    logger.debug(@entry.inspect)
    @userroom = UserRoom.create(room_id: @entry.room_id, user_id: @entry.user_id)
    @entry.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create] #投稿機能はログインユーザーのみ実行できる
  
  

  def index #一覧ページに必要なindexアクション
    @hobbies=Hobby.all 
  end

  def new 
    @hobby=Hobby.new
  end

  def create
    hobby=Hobby.new(hobby_params) #params：ユーザーから送信された情報を受け取る変数
    hobby.user_id=current_user.id #current_user：現在ログインしているuserの情報（レコード）をとってくる機能を実行,[変数.カラム名]

    if hobby.save
      redirect_to :action=>"index" #あるアクションから他のアクションを実行する
    else
      redirect_to :action=>"new"
    end
  end

  

  private
  def hobby_params #hobby_paramsメソッドは、趣味投稿に関するもの以外の情報を含むparamsから、ツイート情報のハッシュだけを絞り込むメソッド
    params.require(:hobby).permit(:body) #user_idのような勝手に変えられてはいけない情報は、permitというメソッドを使って受け取る情報を限定する
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        @user = User.find(params[:following_id])
        current_user.follow(@user)
    end

      def destroy
        @user = User.find(params[:id])
        current_user.unfollow(@user)
      end

    private
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = Room.find(params[:id])
    @posts = Post.where(room_id:@room.id)
  end
  def create
    @room = Room.new(room_params)
    @room.save
    current_user.user_rooms.create(room_id: @room.id)
    redirect_to @room
  end

  def index
      if user_signed_in?
        @room = Room.new
        @rooms = current_user.rooms
        @norooms_id = UserRoom.where.not(user_id:current_user.id)
      end
  end

  private

  def room_params
  　params.require(:room).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id]) 
  end

  def invite
    @user =User.find(current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hobbies/index.html.erb
<h1>Muni.</h1>
<h3>コメント一覧</h3>

<%= link_to "新規投稿へ", new_hobby_path %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<%= link_to "グループ一覧", rooms_path %>

<%= link_to "フォロー", relationships_followings_path%>
<%= link_to "フォロワー", relationships_followers_path%>

app/views/hobbies/new.html.erb
<h1>Muni.</h1>
<h3>投稿ページ</h3>

<%= form_for @hobby do |f| %>

<div class= "field">
    <%=f.label :"趣味" %>
    <%=f.text_field :hobby, :size=>30 %>
</div>

<div class="field">
    <%=f.label :"ジャンル"%>
    <%=f.text_field :genre, :size=>30%>
</div>

<%= f.submit "投稿する" %>

<%end%>
<%= link_to "投稿一覧に戻る", hobbies_path %>

app/views/relationships/views/relationships/create.js.erb
$("#follow_form").html("<%= j(render("users/unfollow")) %>");

app/views/relationships/views/relationships/destory.js.erb
$("#follow_form").html("<%= j(render("users/follow")) %>");

app/views/rooms/index.html.erb
<% if user_signed_in? %>
  <h2>トークルーム作成</h2>
  <%= form_with model: @room do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>

  <h2>参加済トークルーム一覧</h2>
  <% @rooms.each do |room| %>
    <%= link_to room_path(room.id) do %>
    <%= room.name %>
    <% end %>
  <% end %>
<% end %>

<%= link_to "ホームに戻る", hobbies_path %>

app/views/rooms/show.html.erb
<p><%= "ルーム名：#{@room.name}" %></p>
<input type="text" data-behavior="room_speaker" data-user="<%= current_user.id %>" data-room="<%= @room.id %>">
<div id="posts">
 <% @posts.each do |post| %>
  <p><%= post.message %></p>
 <% end %>
</div>



<%= link_to '招待する', inviting_room_path(room_id:params[:room_id], user_id:current_user.id) %>

app/views/users/invite.html.erb
フォロー一覧
<% @user.followings.each do |user| %>フォロー一覧
<% @user.followings.each do |user| %>
 <%= logger.debug(user.inspect) %>
    <div> 
    <%= image_tag user.image_url, size: "60x60" if user.image? %>
    </div>
    <%= link_to entries_room_path(id: params[:id], user_id: user.id), method: :post do %>
        <%= user.name %>
    <% end %>
<% end %>

<p><%= link_to "マイページへ戻る", user_path(current_user.id) %></p>
    <div> 
    <%= image_tag user.image_url, size: "60x60" if user.image? %>
    </div>
    <%= link_to entries_room_path(id: params[:id], user_id: user.id), method: :post do %>
        <%= user.name %>
    <% end %>
<% end %>

<p><%= link_to "マイページへ戻る", user_path(current_user.id) %></p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
  <%= render "follow_form" %>
<h2>ユーザーの投稿一覧</h2>

<% @user.tweets.each do |t| %>
  <%= t.body %>
<% end %>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.hobbies.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>





<%= link_to "Tweet一覧に戻る", hobbies_path %>